// web/src/pages/Guides.jsx
import { useEffect, useState } from "react";
import GuideCard from "../components/GuideCard.jsx";

const Guides = () => {
	const [guides, setGuides] = useState([]);
	const [query, setQuery] = useState("");

	useEffect(() => {
		fetch("http://localhost:4000/api/guides")
			.then((r) => r.json())
			.then(setGuides);
	}, []);

	const search = () => {
		fetch(`http://localhost:4000/api/guides/search?q=${query}`)
			.then((r) => r.json())
			.then(setGuides);
	};

	return (
		<div>
			<h1>Guider</h1>
			<div className="searchrow">
				<input
					value={query}
					onChange={(e) => setQuery(e.target.value)}
					placeholder="Sök på namn eller landskap"
				/>
				<button type="button" className="btn-primary" onClick={search}>
					Sök
				</button>
			</div>
			<div className="grid">
				{guides.map((g) => (
					<GuideCard key={g.id} guide={g} />
				))}
			</div>
		</div>
	);
};

export default Guides;

// client/src/components/Guides.vue
<script setup>
import { onMounted, ref } from "vue";
import { bigFetch } from "../utils/bigFetch.js";
import GuideCard from "./GuideCard.vue";

const guides = ref([]);
const newGuide = ref("");
let result = [];

onMounted(async () => {
	result = await bigFetch("http://localhost:4000/api/guides");
	guides.value = result.data;
});

const searchGuides = async () => {
	result = await bigFetch("http://localhost:4000/api/guides", {
		search: newGuide.value,
	});
	guides.value = result.data;
};
</script>
<template>
    		<div>
			<h1>Guider</h1>
			<div class="searchrow">
				<input v-model="newGuide" placeholder="Sök på namn eller landskap"/>
				<button @click="searchGuides">
					Search
				</button>
			</div>
			<div class="grid">
        <!-- <pre>{{ guides }}</pre> -->
        <GuideCard
 				 	v-for="guide in guides"
  					:key="guide.id"
  					:guide="guide"
					/>
			</div>
		</div>


</template>
