// client/src/components/GuideCard.vue
<script setup>
defineProps({
	guide: {
		required: true,
		type: Object,
	},
});
</script>
<template>
    <div
		class="card"
		
	>
		<h3>
			<!-- <Link to={`/guider/${guide.slug}`}>{guide.title}</Link> -->
			 {{guide.title}}
		</h3>
		<p class="muted">
			{{guide.region}} · {{guide.difficulty}} · {{guide.length_km}} km
		</p>
		<div class="excerpt">
			{{guide.body_html.replace(/<[^>]*>/g, "").slice(0, 180)}}
		</div>
	</div>
</template>
<style scoped>
.card{
    border: 1px solid #ddd;
    padding: 12px;
    border-radius: 4px; 
}
</style>

// web/src/components/GuideCard.jsx
import { Link } from "react-router-dom";

const GuideCard = ({ guide }) => (
	<div
		className="card"
		style={{ border: "1px solid #ddd", padding: 12, borderRadius: 4 }}
	>
		<h3>
			<Link to={`/guider/${guide.slug}`}>{guide.title}</Link>
		</h3>
		<p className="muted">
			{guide.region} · {guide.difficulty} · {guide.length_km} km
		</p>
		<div className="excerpt">
			{guide.body_html.replace(/<[^>]*>/g, "").slice(0, 180)}
		</div>
	</div>
);

export default GuideCard;
